[ADD] eng_fiscal_contact
Engenere/engenere-addons pull request #12
Opened 2024-01-05 11:47 UTC by CristianoMafraJunior

Esse codigo está igual aquele que mandei de manhã no print que ele cria outra page do lado do fiscal, ele esta herdando a view principal

2024-01-05 13:28 UTC, felipemotter commented on eng_fiscal_contact/__manifest__.py
> +    "name": "Contato Fiscal",
Colocar em inglês e no plural

2024-01-05 13:28 UTC, felipemotter commented on eng_fiscal_contact/__manifest__.py
> +    "summary": "Contatos Fiscal",
Explicar melhor qual o intuito de colocar esses campos, colocar em inglês.

2024-01-05 14:12 UTC, CristianoMafraJunior commented on eng_fiscal_contact/__manifest__.py
> +    "name": "Contato Fiscal",
Fiz as alterações como você pediu

2024-01-05 14:12 UTC, CristianoMafraJunior commented on eng_fiscal_contact/__manifest__.py
> +    "summary": "Contatos Fiscal",
fiz as alterações como você pediu

2024-01-05 16:54 UTC, felipemotter requested changes

2024-01-05 16:54 UTC, felipemotter commented on eng_fiscal_contact/models/res_partner.py
> +        domain="[('parent_id', '=', False), '|', ('parent_id', '=', id), ('id', '=', id)]",  # Domain for parent registry and its partners
Este domínio está errado. Ele está pegando todos os `res.partner` que (NÃO tem parent_id) **E** (que TENHAM parent_id igual ao proprio id **OU** id igual id). Eles são conflitantes e nunca haverá um resultado.

Para esse caso queremos que faça um domínio em que apareça apenas `res.partners ` que:
o parent_id seja o contato que você está editando ou o parent_id seja o parent_id do record que você está editando.

2024-01-05 19:19 UTC, antoniospneto commented on eng_fiscal_contact/models/res_partner.py
> +                raise exceptions.ValidationError('Todos os contatos são obrigados a ter um endereço de e-mail.')
eu penso que a mensagem aqui podia ser um pouco mais especifica, todos os contatos **fiscais** são obrigados a ter um endereço de e-mail.

O correto é por a mensagem em inglês também, a tradução a gente faz em uma outra camada

2024-01-05 19:21 UTC, antoniospneto commented on eng_fiscal_contact/models/res_partner.py
> +        string='Contatos',
o contatos por em ingles tbm

2024-01-05 19:26 UTC, CristianoMafraJunior commented on eng_fiscal_contact/models/res_partner.py
> +                raise exceptions.ValidationError('Todos os contatos são obrigados a ter um endereço de e-mail.')
Ok irei fazer a alteração

2024-01-05 19:39 UTC, antoniospneto commented on eng_fiscal_contact/models/res_partner.py
> +        for contato in self.fiscal_contact_ids:
não tinha visto antes, mas aqui tbm por em ingles

2024-01-05 19:41 UTC, antoniospneto commented on eng_fiscal_contact/views/res_partner_views.xml
> +                <group string="Contatos Fiscal" name="fiscal_contacts">
aqui tbm pode por em ingles, em seguida vamos ensinar a incluir as traduções

2024-01-08 10:15 UTC, CristianoMafraJunior commented on eng_fiscal_contact/views/res_partner_views.xml
> +                <group string="Contatos Fiscal" name="fiscal_contacts">
Duas alterações feitas

2024-01-08 12:52 UTC, antoniospneto commented on eng_fiscal_contact/models/res_partner.py
> +        column2='contato_id',
o nome dessa coluna, pode ser em ingles também, e acho que fica mais intuitivo chamar de fiscal_contact_id

2024-01-08 13:23 UTC, CristianoMafraJunior commented on eng_fiscal_contact/models/res_partner.py
> +        column2='contato_id',
Alteração feita

2024-03-04 13:24 UTC, merged