[ADD] l10n_br_due_date - change billing date
Engenere/engenere-addons pull request #6
Opened 2023-12-21 11:59 UTC by CristianoMafraJunior

Criação do modulo l10n_br_due_date para alteração do formato da coluna de data de faturamento para o padrão dd-mm-yyyy

2023-12-21 12:22 UTC, antoniospneto commented
Aqui como estamos estendendo o módulo account nativo o nome podia ser ser account_due_date_usability

2023-12-21 12:51 UTC, CristianoMafraJunior commented
Nome do modulo alterado

2023-12-22 12:06 UTC, antoniospneto approved these changes

2024-01-04 13:37 UTC, felipemotter commented on l10n_br_account_due_date_usability/views/due_date_views.xml
> +            <xpath expr="//field[@name='invoice_data_due']" position="attributes">
Olá Cristiano, acredito que como é uma referência simples, procurando um campo pelo name, usar field ao invés de xpath diretamente ficaria mais organizado e legível.

2024-01-04 13:38 UTC, felipemotter requested changes

2024-01-04 13:38 UTC, felipemotter commented on l10n_br_account_due_date_usability/views/due_date_views.xml
> +    </record>
Consegue fazer a alteração que solicitei?

2024-01-04 15:00 UTC, CristianoMafraJunior commented on l10n_br_account_due_date_usability/views/due_date_views.xml
> +            <xpath expr="//field[@name='invoice_data_due']" position="attributes">
Fiz alteração passando o Field

2024-01-04 16:17 UTC, felipemotter approved these changes

2024-01-04 16:17 UTC, merged